#!/usr/bin/env python3
"""Regenerate the PROGMEM logo byte arrays embedded in src/main.cpp.

Why this exists: main.cpp has no filesystem (LittleFS/SPIFFS) - deliberately
deferred, see DECISIONS.md - so the two logo PNGs referenced by
web/ys-boot.html (ys-logo-full.png, ys-logo-topbar.png) are baked into
main.cpp as byte arrays and served via dedicated routes
(handleLogoFull/handleLogoTopbar) instead of from a file.

Run this whenever web/ys-logo-full.png or web/ys-logo-topbar.png change:

    python scripts/embed_logos.py

It rewrites the block between the LOGO_ARRAYS_START/END markers in
src/main.cpp in place - nothing else in the file is touched. If a marker
is missing (e.g. after unrelated edits move things around), it aborts
without changing the file rather than guessing where to insert.
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MAIN_CPP = REPO_ROOT / "src" / "main.cpp"
LOGOS = [
    ("LOGO_FULL_PNG", REPO_ROOT / "web" / "ys-logo-full.png"),
    ("LOGO_TOPBAR_PNG", REPO_ROOT / "web" / "ys-logo-topbar.png"),
]

START = "// LOGO_ARRAYS_START (generated by scripts/embed_logos.py - do not hand-edit)"
END = "// LOGO_ARRAYS_END"
PLACEHOLDER = "// LOGO_ARRAYS_PLACEHOLDER"


def format_array(name: str, data: bytes) -> str:
    lines = [f"const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(data), 20):
        chunk = data[i : i + 20]
        lines.append("  " + "".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    lines.append(f"const size_t {name}_LEN = {len(data)};")
    return "\n".join(lines)


def main():
    for name, path in LOGOS:
        if not path.exists():
            print(f"error: {path} not found", file=sys.stderr)
            sys.exit(1)

    blocks = []
    for name, path in LOGOS:
        data = path.read_bytes()
        blocks.append(format_array(name, data))
        print(f"{path.name}: {len(data)} bytes -> {name}[]")
    generated = START + "\n" + "\n".join(blocks) + "\n" + END

    text = MAIN_CPP.read_text(encoding="utf-8")

    if PLACEHOLDER in text:
        text = text.replace(PLACEHOLDER, generated)
    elif START in text and END in text:
        text = re.sub(
            re.escape(START) + r".*?" + re.escape(END),
            generated,
            text,
            flags=re.DOTALL,
        )
    else:
        print(
            "error: neither the placeholder nor existing START/END markers "
            "were found in src/main.cpp - not touching the file",
            file=sys.stderr,
        )
        sys.exit(1)

    MAIN_CPP.write_text(text, encoding="utf-8")
    print(f"Updated {MAIN_CPP}")


if __name__ == "__main__":
    main()
