#!/usr/bin/env python3
"""Regenerate the base64 @font-face block embedded in web/ys-boot.html.

Why this exists: the controller's own WiFi AP (SmartBrew-Test) has no
internet uplink, so the page's original <link> to fonts.googleapis.com
would silently fail to load on a real phone - it only ever worked during
dev-machine testing on a normal network. Fonts are embedded as base64
data URIs instead, same reasoning as the logo PNGs.

Source .woff2 files live in web/fonts/ - each is the Latin-only subset
already served by Google Fonts as its "latin" unicode-range block (no
Hebrew/Cyrillic/Devanagari needed on this page), fetched once and
committed here so this script never needs network access to run.

Run this after adding/removing a weight in web/fonts/:

    python scripts/embed_fonts.py

It rewrites the block between the FONTS_START/END markers inside
web/ys-boot.html's first <style> block in place. If a marker is missing,
it aborts without changing the file rather than guessing where to insert.
Note this only updates web/ys-boot.html - run embed_boot_html.py
afterwards to propagate the change into src/main.cpp, same two-step flow
as a logo change.
"""
import base64
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BOOT_HTML = REPO_ROOT / "web" / "ys-boot.html"
FONTS_DIR = REPO_ROOT / "web" / "fonts"

# (family name, weight, filename)
FONTS = [
    ("Rajdhani", 400, "rajdhani-400.woff2"),
    ("Rajdhani", 500, "rajdhani-500.woff2"),
    ("Rajdhani", 600, "rajdhani-600.woff2"),
    ("Rajdhani", 700, "rajdhani-700.woff2"),
    ("Share Tech Mono", 400, "sharetechmono-400.woff2"),
]

START = "  /* FONTS_START (generated by scripts/embed_fonts.py - do not hand-edit)"
END = "  /* FONTS_END */"


def font_face(family: str, weight: int, path: Path) -> str:
    data = base64.b64encode(path.read_bytes()).decode("ascii")
    return (
        "  @font-face {\n"
        f"    font-family: '{family}';\n"
        "    font-style: normal;\n"
        f"    font-weight: {weight};\n"
        "    font-display: swap;\n"
        f"    src: url(data:font/woff2;base64,{data}) format('woff2');\n"
        "  }"
    )


def main():
    for _, _, filename in FONTS:
        path = FONTS_DIR / filename
        if not path.exists():
            print(f"error: {path} not found", file=sys.stderr)
            sys.exit(1)

    text = BOOT_HTML.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(
            "error: FONTS_START/END markers not found in web/ys-boot.html - "
            "not touching the file",
            file=sys.stderr,
        )
        sys.exit(1)

    start_idx = text.index(START)
    end_idx = text.index(END) + len(END)

    blocks = [font_face(family, weight, FONTS_DIR / filename) for family, weight, filename in FONTS]
    total_bytes = sum((FONTS_DIR / f).stat().st_size for _, _, f in FONTS)

    generated = (
        START + "\n"
        "     Rajdhani 400/500/600/700 + Share Tech Mono 400, Latin subset only (no\n"
        "     Hebrew/Cyrillic/Devanagari on this page - matches the logo's\n"
        "     size-reduction trick). Embedded as base64 so this page needs zero\n"
        "     internet access, not even for fonts - the controller's AP has no\n"
        "     internet uplink, so an external <link> to fonts.googleapis.com would\n"
        "     just silently fail to load on a real phone. Source .woff2 files live\n"
        "     in web/fonts/ - edit those (or re-run scripts/embed_fonts.py after\n"
        "     changing which weights/families are needed), never this block by\n"
        "     hand. */\n"
        + "\n".join(blocks)
        + "\n"
        + END
    )

    text = text[:start_idx] + generated + text[end_idx:]
    BOOT_HTML.write_text(text, encoding="utf-8")
    print(f"Embedded {len(FONTS)} fonts ({total_bytes} bytes raw) into {BOOT_HTML}")


if __name__ == "__main__":
    main()
