#!/usr/bin/env python3
"""Regenerate the PROGMEM audio-clip byte arrays embedded in src/main.cpp.

Why this exists: main.cpp has no filesystem (LittleFS/SPIFFS) for static
assets - deliberately deferred, see DECISIONS.md - so brew-stage alert mp3s
are baked into main.cpp as byte arrays and served by the single generic
handleAudioFile() route (GET /audio?file=<name>.mp3), the same pattern
scripts/embed_logos.py already uses for the two logo PNGs.

Run this whenever a file in web/audio/ is added, removed, or replaced:

    python scripts/embed_audio.py

It rewrites the block between the AUDIO_ARRAYS_START/END markers in
src/main.cpp in place - nothing else in the file is touched. If neither the
placeholder nor the markers are found (e.g. after unrelated edits move
things around), it aborts without changing the file rather than guessing
where to insert. NOTE (2026-09): the voice-audio system is currently removed
from main.cpp (only the placeholder marker remains) - do not run this until
the microSD plan is underway; the /audio route and handleAudioFile() also
need restoring then (see the marker's comment in main.cpp). Adding a new
clip, once reinstated, needs no C++ changes at all: drop the
mp3 in web/audio/, rerun this script, rebuild - handleAudioFile() already
serves whatever is in the generated AUDIO_CLIPS table.
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MAIN_CPP = REPO_ROOT / "src" / "main.cpp"
AUDIO_DIR = REPO_ROOT / "web" / "audio"

START = "// AUDIO_ARRAYS_START (generated by scripts/embed_audio.py - do not hand-edit)"
END = "// AUDIO_ARRAYS_END"
PLACEHOLDER = "// AUDIO_ARRAYS_PLACEHOLDER"
STRUCT = "struct AudioClip { const char *filename; const uint8_t *data; size_t len; };"


def array_name(filename: str) -> str:
    stem = filename.rsplit(".", 1)[0]
    safe = re.sub(r"[^A-Za-z0-9_]", "_", stem)
    return f"AUDIO_{safe}"


def format_array(name: str, data: bytes) -> str:
    lines = [f"const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(data), 20):
        chunk = data[i : i + 20]
        lines.append("  " + "".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    lines.append(f"const size_t {name}_LEN = {len(data)};")
    return "\n".join(lines)


def main():
    files = sorted(AUDIO_DIR.glob("*.mp3")) if AUDIO_DIR.exists() else []

    blocks = []
    clip_rows = []
    for path in files:
        data = path.read_bytes()
        name = array_name(path.name)
        blocks.append(format_array(name, data))
        clip_rows.append(f'  {{"{path.name}", {name}, {name}_LEN}},')
        print(f"{path.name}: {len(data)} bytes -> {name}[]")

    if not files:
        print(f"warning: no .mp3 files found in {AUDIO_DIR} - generating an empty table")

    if clip_rows:
        table = "const AudioClip AUDIO_CLIPS[] = {\n" + "\n".join(clip_rows) + "\n};\n"
        table += f"const size_t AUDIO_CLIPS_COUNT = {len(clip_rows)};"
    else:
        # A zero-size array isn't portable C++. Declare an unused one-entry
        # placeholder and keep the count at 0 so handleAudioFile()'s loop
        # never looks at it.
        table = 'const AudioClip AUDIO_CLIPS[1] = { {"", nullptr, 0} };\n'
        table += "const size_t AUDIO_CLIPS_COUNT = 0;"

    generated = START + "\n" + STRUCT + "\n" + "\n".join(blocks) + ("\n" if blocks else "") + table + "\n" + END

    text = MAIN_CPP.read_text(encoding="utf-8")

    if PLACEHOLDER in text:
        text = text.replace(PLACEHOLDER, generated)
    elif START in text and END in text:
        text = re.sub(
            re.escape(START) + r".*?" + re.escape(END),
            generated,
            text,
            flags=re.DOTALL,
        )
    else:
        print(
            "error: neither the placeholder nor existing START/END markers "
            "were found in src/main.cpp - not touching the file",
            file=sys.stderr,
        )
        sys.exit(1)

    MAIN_CPP.write_text(text, encoding="utf-8")
    print(f"Updated {MAIN_CPP}")


if __name__ == "__main__":
    main()
