#!/usr/bin/env python3
"""Regenerate the PROGMEM PAGE_HTML string embedded in src/main.cpp from
web/ys-boot.html.

Why this exists: main.cpp has no filesystem (LittleFS/SPIFFS) - deliberately
deferred, see DECISIONS.md - so the page served by handleRoot() is baked
into main.cpp as a raw string literal. Earlier this was kept in sync by
hand, which silently drifted (comments got stripped when the block was
first typed in) - this script makes web/ys-boot.html the single source of
truth: it copies that file's bytes verbatim, nothing is retyped.

Run this whenever web/ys-boot.html changes:

    python scripts/embed_boot_html.py

It rewrites the block between the PAGE_HTML_START/END markers in
src/main.cpp in place - nothing else in the file is touched. If a marker
is missing (e.g. after unrelated edits move things around), it aborts
without changing the file rather than guessing where to insert.
"""
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MAIN_CPP = REPO_ROOT / "src" / "main.cpp"
BOOT_HTML = REPO_ROOT / "web" / "ys-boot.html"

START = "// PAGE_HTML_START (generated by scripts/embed_boot_html.py - do not hand-edit)"
END = "// PAGE_HTML_END"
DELIM = "HTML"  # raw string delimiter: R"HTML( ... )HTML"


def main():
    if not BOOT_HTML.exists():
        print(f"error: {BOOT_HTML} not found", file=sys.stderr)
        sys.exit(1)

    html = BOOT_HTML.read_text(encoding="utf-8")
    closing = f"){DELIM}\""
    if closing in html:
        print(
            f"error: {BOOT_HTML} contains the raw-string terminator ){DELIM}\" "
            "- pick a different delimiter in both this script and main.cpp",
            file=sys.stderr,
        )
        sys.exit(1)

    generated = (
        f"{START}\n"
        f'const char PAGE_HTML[] PROGMEM = R"{DELIM}(\n'
        f"{html}"
        f"){DELIM}\";\n"
        f"{END}"
    )

    text = MAIN_CPP.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(
            "error: PAGE_HTML_START/END markers not found in src/main.cpp - "
            "not touching the file",
            file=sys.stderr,
        )
        sys.exit(1)

    start_idx = text.index(START)
    end_idx = text.index(END) + len(END)
    text = text[:start_idx] + generated + text[end_idx:]

    MAIN_CPP.write_text(text, encoding="utf-8")
    print(f"Embedded {BOOT_HTML} ({len(html)} bytes) into {MAIN_CPP}")


if __name__ == "__main__":
    main()
